<?php
require_once '../header.php';
html_header('Observation');
?>
            <tbody>
                <tr>
                    <td style="vertical-align:top">
                        <div style="height:44px"></div>
                        <table style="padding:2px">
                            <tr>
                                <th style="text-align:left">
                                    OBSERVATION
                                </th>
                            </tr>
                            <tr>
                                <td style="font-size:large;text-align:justify">
                                    Despite Chennai being the fifth largest city in terms of Area, Chennai is  the metro that generates the largest per capita amount of waste in the country. Chennai, which generates 6,404 tonnes of waste daily, the garbage generated by an average household includes 25% recyclable waste, 60% organic waste and 10% hazardous waste. At least 30% of garbage goes into drains, while many vacant plots and pavements have become unofficial dump yards. The city, with about 730 hospitals, also generates an average of 9,898kg of biomedical waste a day.
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>